version: '3.3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql/data
    ports:
      - 3307:3306
